
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    evictionHard:
      nodefs.available: "0%"
kubeadmConfigPactchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta2
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: my-hostname
nodes:
  - role: control-plane
    image: kindest/node-arm64:v1.22.0
  - role: worker
  - role: worker
  - role: worker