# permissions for end users to edit applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-editor-role
rules:
- apiGroups:
  - app.my.domain
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.my.domain
  resources:
  - applications/status
  verbs:
  - get
