// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/darrenli6/GolangStudy/GoAdvanced/go-zero/user/rpc/internal/logic"
	"github.com/darrenli6/GolangStudy/GoAdvanced/go-zero/user/rpc/internal/svc"
	"github.com/darrenli6/GolangStudy/GoAdvanced/go-zero/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Auth(ctx context.Context, in *user.UserAuthRequest) (*user.UserAuthReply, error) {
	l := logic.NewAuthLogic(ctx, s.svcCtx)
	return l.Auth(in)
}
