// Code generated by goctl. DO NOT EDIT.
package types

type ProductListRequest struct {
	BaseRequest
}

type ProductListReply struct {
	List  []*ProductListBaisc `json:"list"`
	Count int64               `json:"count"`
}

type ProductListBaisc struct {
	Identity  string `json:"identity"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
}

type DeviceListRequest struct {
	BaseRequest
}

type DeviceListBasic struct {
	Identity       string `json:"identity"`
	Name           string `json:"name"`
	Key            string `json:"key"`
	Secret         string `json:"secret"`
	ProductName    string `json:"product_name"`
	LastOnlineTime int64  `json:"last_online_time"`
}

type DeviceListReply struct {
	List  []*DeviceListBasic `json:"list"`
	Count int64              `json:"count"`
}

type BaseRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:",optional"`
	Name string `json:"name,optional"`
}
